version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: skill-search-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ../data:/data:ro  # Mount data directory (read-only)
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials (read-only)
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - skill-search-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: skill-search-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
      - ../shared:/shared:ro  # Mount shared styles (read-only)
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable hot reload in Docker
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - skill-search-network

networks:
  skill-search-network:
    driver: bridge
